### ISSUE TITLE
Features to support runnign as array jobs on a cluster

### ISSUE THREAD

**Issue by mronkko** [philchalmers/SimDesign#33] opened 2024-03-20 14:31 UTC
I am running my simulations as array jobs on a computer cluster. I know that I could, in principle, set up an array job backend using futures, but this is not a very flexible approach. Ideally, I would be able to run array jobs using SimDesing. 

Let's assume that I have a simulation with 1000 conditions and 1000 replications each and I am runnign on a cluster where I have 10 000 cores available. I would like to split the simulation so that each core runs 100 replications of one condition. This is controlled by array job number so that e.g. job number 1 means replications 1-100 of design 1, job number 2 means replications 101-200 of desing 2, and so on. 

The simulation should be ideally fully reproducible so that no matter how I split the work, I will get the same results. This means that I cannot split the simulation into chunks of 10*100 replications without explicitly considering how seeds are managed because otherwise, the results would be different from just running 1*1000 replications. The computational time is constrained so that I can reserve one core for at most 4 hours and need to exit before that, or otherwise, the job will be killed.

To implement my workflow with SimDesign, I would need a couple of features:

1) Setting maximum execution time and aborting the simulation saving the incomplete results when the maximum execution time has been exceeded by SimDesign. I believe this might be useful for researchers who run simulations in computer classes, for example. SimDesign already has a way to continue from incomplete replications.

2) Running a subset of replications while maintaining reproducibility. This could work, for example, by generating a list of 1000 seeds randomly and then setting a seed for each replication. This way, it would not matter in which order I run the replications, and the replications would still be reproducible. This could be implemented by allowing the seed argument to take a list of vectors of seeds so that each vector contains 1000 seeds each used for each replication, and the list elements correspond to the conditions. Ideally, this would be done internally, though, and I would just tell simDesign to, e.g., run replication 201-300 out of 1000. 

I have custom code that implements this approach here https://osf.io/5uep6 (See: # Multiple Monte Carlo simulation, parallel execution on a computer cluster ====)

**Comment by philchalmers** [comment] 2024-03-22 14:55
This is an interesting feature that I had not considered (having access to many more workers than replications per condition is not a common occurrence in my experience). This is also strongly related to issue #32, which I've closed in favour of addressing this issue as this appears to be an application where parallelizing across the design conditions is desirable. 

I like the idea of jointly distributing the `design` rows and `replications` across nodes and collecting the information once the whole job is complete, though the optimal approach to doing so will require quite a bit of internal modifications. Nevertheless, I think it is feasible.

**Comment by mronkko** [comment] 2024-03-22 16:28
When running on cluster, I would be managing parallelization myself. I just need the ability to run subset of simulations and manage seeds so that the analysis is reproducible regardless how I distribute the computation. Ideally I would want to run something like this

```
#-------------------------------------------------------------------

library(SimDesign)

Design <- createDesign(factor1 = NA,
                       factor2 = NA)

REPLICATIONS <- 1000
REPLICATION_SETS <- 10

# Read the array job number from the command line if given. Otherwise run all
# conditions and all replication sets.

args <- commandArgs(trailingOnly = TRUE)

if (length(args) > 0) {
  
  # Array job ID is a sequential number that the computer cluster uses
  # to control which part of the simulation is executed. We will now map
  # the array job ID to design number and replication set.
  
  arrayJobID <- as.numeric(args[1])
  designNumber <- ceiling(arrayJobID/REPLICATION_SETS)
  
  replication_set <- (arrayJobID - 1) %% REPLICATION_SETS + 1
  replication_set_size <- ceiling(REPLICATIONS/REPLICATION_SETS)
    
  # Split the replications in sets and choose the set to run
  
  replications <- (replication_set_size * (replication_set-1) +1 ): # First rep
    min(replication_set_size * replication_set, REPLICATIONS)       # Last rep
  
  # Subset specification 
  
  subset <- list(design = designNumber,
                 replication_set = replication_set)
}
else {
  # No subsetting, run everything
  subset <- NULL
}

#-------------------------------------------------------------------

Generate <- function(condition, fixed_objects = NULL) {
  dat <- data.frame()
  dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
  ret <- nc(stat1 = NaN, stat2 = NaN)
  ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
  ret <- c(bias = NaN, RMSE = NaN)
  ret
}

#-------------------------------------------------------------------

res <- runSimulation(design=Design, replications=REPLICATIONS,
                     generate=Generate, analyse=Analyse, 
                     subset = subset, # Specify which subset to run
                     max_time = 3.75) # Maximum time to run before aborting

#-------------------------------------------------------------------

# Save subset to disk

if(!is.null(subset)){
  save(res,paste("Design ", designNumber,
                 " Replications ", min(replications), "-", max(replications),
                 ".Rdata",sep=""))
}

# Once everythign is done, combine with aggregate_simulations()
```

Splitting replications over different nodes is not just a hypothetical scenario. We just published a paper in Psychological Methods (not online yet) where we estimated latent interaction models that took about 30 minutes per replication. We started by running 100 replications on node (out of 1000) and in the end ran some of the more difficult conditions with 5 replications per node. 

https://osf.io/pwdj2

**Comment by philchalmers** [comment] 2024-03-25 16:22
I see what you're saying here, though I'm not a huge fan of the `subset` approach being passed to `runSimulation()` since the seed management responsibility would become obscure, and it's less clear how the replication balance would be managed without further modifications. 

Here's an approach that could work under the latest dev version, which includes a few generalizations to `createDesign()` and `aggregate_simulations()` for replicating conditions with the purpose of independent distributions of the conditions.

```r
# Example where each row condition is repeated, evaluated independently,
# and later collapsed into a single analysis object

# Each condition repeated four times (hence, replications
# should be set to desired.reps/4)
Design <- createDesign(N  = c(30, 60),
                    mu = c(0,5),
                    repeat_conditions = 4L)

#-------------------------------------------------------------------
Generate <- function(condition, fixed_objects = NULL) {
 dat <- with(condition, rnorm(N, mean=mu))
 dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
 ret <- c(mean=mean(dat), SD=sd(dat))
 ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
 ret <- colMeans(results)
 ret
}

#-------------------------------------------------------------------

# Generate fixed seeds to be distributed
set.seed(1234)
seeds <- gen_seeds(Design)
seeds

# replications vector (constant is fine if the same across conditions;
# below is vectorized to demonstrate that this could change)
replications <- rep(250, nrow(Design))

# create directory to store all final simulation files
dir.create('sim_files/')

# distribute jobs independently (explicitly parallelize here on cluster)
sapply(1:nrow(Design), \(i) {
  runSimulation(design=Design[i, ], replications=replications[i],
             generate=Generate, analyse=Analyse, summarise=Summarise,
             filename=paste0('sim_files/job-', i))
})

# aggregate into single object
sim <- aggregate_simulations(files = paste0('sim_files/job-',
                                  1:nrow(Design), ".rds"))
sim
```

The `sapply()` portion is where the jobID information would go, though in this case all you should need is `arrayJobID <- as.numeric(args[1])` to index out the correct row condition from `Design`. Let me know what you think, or if other modifications should be made to better support this feature.

**Comment by mronkko** [comment] 2024-03-26 05:23
This is helpful. However, there is one issue that would still need to be addressed. For example, in this project https://osf.io/pwdj2, some of the more challenging conditions can take substantially longer to run (like 100 times slower) than the easier conditions. How I started by running the simulation as batches of 100 replications to split it over 5800 nodes. This was sufficient to complete most of the conditions before hitting the computation time limit. Then I decrease the batch size to 25 to run the remainder of the replications and then finally to 10 and 5 replications per node. 

In the current implementation of SimDesign, I can support this workflow, but reproducibility would be a challenge. For example, I could run the first batch of replications with seed 1 and batch size 100. Then I would count how many replications are missing and rerun with seed 2 and batch size 25 to get closer to the 1000 replications per condition that I want. However, to make this reproducible, I would need to record how many replications each run produces for each design. 

I currently solve the reproducibility problem  by creating a vector containing replication-specific seeds (https://osf.io/pwdj2):

```
  # Initialize seeds. We will use a pre-specified seed for each replication
  # to make it possible to reproduce a single replication
  
  set.seed(designNumber)
  replicationSeeds <- (runif(REPLICATIONS)*.Machine$integer.max)
```

A really awkward workaround would be to run SimDesign with repeat_conditions = 1000 and replications = 1, but this would produce a huge number of small files.

**Comment by philchalmers** [comment] 2024-03-26 14:12
> In the current implementation of SimDesign, I can support this workflow, but reproducibility would be a challenge. For example, I could run the first batch of replications with seed 1 and batch size 100. Then I would count how many replications are missing and rerun with seed 2 and batch size 25 to get closer to the 1000 replications per condition that I want. However, to make this reproducible, I would need to record how many replications each run produces for each design.

Right, so I suppose this is where the `max_time` portion should come in, which unfortunately would only work for single-core implementations due to the nature of the R interpreter. I suppose what should happen is if `max_time` were specified then the simulation should run each independent condition within this time limit, though when the complete replication set is unable to complete within this limit then all the results up to this point should returned with a warning message (hence, the observed replications will be less than the target reps). After that, you'd see something like this

```r
sim <- aggregate_simulations(files = paste0('sim_files/job-',
                                  1:nrow(Design), ".rds"))
sim

      N        p REPLICATIONS SIM_TIME RAM_USED       SEED COMPLETED               
  <dbl>    <dbl>        <int> <chr>    <chr>         <int> <chr>                   
1    10 0                1000 2.03h    219.2 Mb 1684466911 Tue Mar 26 09:56:10 2024
2    20 0                  20 4.03h    219.2 Mb 1120908474 Tue Mar 26 09:56:10 2024
3    30 0.033333         1000 2.03h    219.2 Mb  303373395 Tue Mar 26 09:56:10 2024
```

in which case you can gauge which of the simulations missed the target reps, how many were successfully completed, and the approximate distribution load to use for the next run after taking a subset of the results and expanding the row conditions accordingly for redistribution. The main issue, at least as far as I can telll, is that `max_time` would have to be safely less than the cluster's timeout (at least 80-90% of the actual max time), otherwise you run the risk of throwing away valuable computing time if `max_time` exceeds the clusters true kill time.... 

Feels clunky IMHO, though I'm open to suggestions if you can foresee a better route.

**Comment by mronkko** [comment] 2024-03-27 05:18
Excactly. Two comments:

1. The single-core implementation is not actually a relevant limitation because of how the cluster that I use works. (I assume they work generally like this.) The time limit concerns a workload for a reservation of a single core and not the full runtime of a simulation. For example, if I split the simulation into 20,000 jobs, each job can take 4 hours (or what ever limit I specify). If the cluster has 5,000 cores available, then the entire run might take around 16 hours at most. I do this by specifying an array job, which uses job IDs to control which part of the simulation is run, but it would work the same way if using the slurm future backend. 
2. Yes, the maxt_ime needs to be less than cluster maximum. I can see two ways of addressing this. a) SimDesign keeps track of how long a replication takes at most and then stops execution if it seems possible that runtime will be exceeded. b) SimDesign stops execution after the time limit has been exceeded, and the documentation tells that it is the user's responsibility to consider what kind of safety margin is needed to avoid jobs being killed. I think option b is better. In practice, I set my time limit to 4 hours when requesting computer time and abort simulation in R code after 3.75 hours of computer time. I might reduce this for some of the final runs where the 15-minute safety margin is not sufficient.

**Comment by philchalmers** [comment] 2024-03-28 00:47
Latest version should support this structure now. Here's a working demonstration:

```r
# Example where each row condition is repeated, evaluated independently,
# and later collapsed into a single analysis object

# Each condition repeated four times (hence, replications
# should be set to desired.reps/4)
Design <- createDesign(N  = c(30, 60),
                       mu = c(0,5))
Design$slow <- c(TRUE, FALSE, FALSE, TRUE)
Design4 <- expandDesign(Design, 4L)

#-------------------------------------------------------------------
Generate <- function(condition, fixed_objects = NULL) {
    dat <- with(condition, rnorm(N, mean=mu))
    dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
    if(condition$slow) Sys.sleep(1/2)
    ret <- c(mean=mean(dat), SD=sd(dat))
    ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
    ret <- colMeans(results)
    ret
}

#-------------------------------------------------------------------

# Generate fixed seeds to be distributed
set.seed(1234)
seeds <- gen_seeds(Design)
seeds

# replications vector (constant is fine if the same across conditions;
# below is vectorized to demonstrate that this could change)
replications <- rep(100, nrow(Design))

dir.create('sims/')

# distribute jobs independently (explicitly parallelize here on cluster)
out <- sapply(1:nrow(Design), \(i) {
    runSimulation(design=Design[i, ], replications=replications[i],
                  generate=Generate, analyse=Analyse, summarise=Summarise,
                  control = list(max_time = 1/(60*30)), # specified in hours
                  filename = paste0('sims/job-', i))
})

do.call(rbind, out)
# A tibble: 4 × 11
      N    mu slow       mean      SD REPLICATIONS SIM_TIME RAM_USED       SEED COMPLETED         ERRORS
  <dbl> <dbl> <lgl>     <dbl>   <dbl>        <dbl> <chr>    <chr>         <int> <chr>              <int>
1    30     0 TRUE  0.027945  1.0156             4 2.75s    352.8 Mb  368872581 Wed Mar 27 16:46…      1
2    60     0 FALSE 0.0075091 0.99426          100 0.51s    353.3 Mb  485569970 Wed Mar 27 16:46…     NA
3    30     5 FALSE 5.0040    0.99709          100 0.24s    353.4 Mb 2139533607 Wed Mar 27 16:46…     NA
4    60     5 TRUE  4.9715    0.96186            4 3.50s    353.4 Mb  697610254 Wed Mar 27 16:46…      1

##############
# (separate file) aggregate into single object once all jobs are completed
sim <- aggregate_simulations(files = paste0('sims/job-',
                                            1:nrow(Design), ".rds"))
sim

# A tibble: 4 × 10
      N    mu slow       mean      SD REPLICATIONS SIM_TIME RAM_USED COMPLETED                ERRORS
  <dbl> <dbl> <lgl>     <dbl>   <dbl>        <dbl> <chr>    <chr>    <chr>                     <int>
1    30     0 TRUE  0.027945  1.0156             4 2.75s    352.8 Mb Wed Mar 27 16:46:45 2024      1
2    60     0 FALSE 0.0075091 0.99426          100 0.51s    353.3 Mb Wed Mar 27 16:46:49 2024     NA
3    30     5 FALSE 5.0040    0.99709          100 0.24s    353.4 Mb Wed Mar 27 16:46:51 2024     NA
4    60     5 TRUE  4.9715    0.96186            4 3.50s    353.4 Mb Wed Mar 27 16:46:56 2024      1
```

**Comment by mronkko** [comment] 2024-03-28 06:11
Thanks. This addresses the time limit. However, I am not sure about reproducibility. Consider the two scenarios below:

### Scenario 1

Let's assume that we want to run a slow simulation with 100 replications. We are not quite sure how long it takes, so we request 100 replications and just see how many we get. Let's further assume that the first run of the simulation gives us 63 completed replications and we rerun the simulation to get the remaining 37 from the second run. 

Now, let's assume that we want to reproduce the simulation. We rerun the code with the same seed but now get 62 completed replications before running out of time and need to do the remaining 38 in a second run. This is not a hypothetical scenario because there might be background processes take processor time. Also computer clusters often have different kinds of nodes and in one run the job might be allocated to a slower node.

How would reproducibility of random number seeds work in this case?

One additional factor that complicates reproducibility is that the analyse function might use random numbers. For example, if we did Bayesian estimation.

### Scenario 2

Let's assume that we want to run a slow simulation with 100 replications. We are not quite sure how long it takes, so we request 100 replications and just see how many we get. Let's further assume that the simulation was much slower than we thought and the first run of the simulation gives us 6 completed replications. We realize that instead of running 100 replications on a single node, it makes sense to switch strategy and split this computation into 10 batches of ten replications each. We could discard the 6 replications but that would be wasting computer resources. So we have 6 repliucations calculated using one strategy and remaining 94 using another strategy. 

How would reproducibility of random number seeds work in this case?

**Comment by philchalmers** [comment] 2024-03-28 12:34
For Scenario 1, the seed used on the initial 100 replication run would be the seed used for reproducibility of the 63 requested replications, while the remaining 37 replication would be evaluated on a second batch and assigned a unique seed here too. In this post-replication of the initial results happens on a condition by condition with the initial and secondary specified seed. If the results are allocated to a slower node then the first $n$ of the results will be identical but the rest will not be available due to the time out. 

In general I would treat this as a fringe case as this issue is going to be present for every conceivable simulation being run on different computing architecture. Also, if you're really that worried about reproducibility you can always dump the entire `.Random.seed` states from each simulation replication to an external folder via `runSimulation(..., save_seeds)` and manually reproduce each replication independently (this is overkill, but possible). Note that the use of random numbers and such within the analyze step has no influence on the issue.

For Scenario 2, same as above. The initial 100 replication run was assigned a unique seed, which gives 6 valid replication and is reproducible from that seed. The remaining 94 replications, split evenly across a second run, would be assigned their own seed that is different from the initial run. The secondary run would have 10 batches submitted, with all but one batch requesting 10 replications (the last one only requests 4 replications). When done, `aggregage_simulations()` combines the results, and if the need arises to replicate the exact simulation job just stack the 11 conditions into a `design` object with the associated seeds.

**Comment by philchalmers** [comment] 2024-03-30 13:36
I'm thinking this issue is closed at this point, sans a few structural changes that I'm thinking to add for smoothing out the process given a more canonical extractions of the following:

```r
args <- commandArgs(trailingOnly = TRUE)

if (length(args) > 0) {
   # index row elements manually
   arrayJobID <- as.numeric(args[1])
   design <- Design[arrayJobID, ]
   reps <- replications[arrayJobID]
   filename <- paste0('sim_files/job-', arrayJobId)
    runSimulation(design=design, replications=reps,
                 generate=Generate, analyse=Analyse, summarise=Summarise,
                 filename=filename)
} else {
  # run normally
  runSimulation(design=Design, replications=replications,
             generate=Generate, analyse=Analyse, summarise=Summarise,
             filename='main_sim')
}
```
Taking subsets given `arrayJobID` and renaming stored files in a safe way is something that I should be automating to avoid complications, so I'll add this to the TODO list prior to the next major release. 

However, I'm interested in what method is required for using `args <- commandArgs(trailingOnly = TRUE)` in the first place. In the past, I've used slurm distributions which has a similar

```r
arrayJobID <- Sys.getenv("SLURM_ARRAY_TASK_ID")
```

Do you know what type of array job distribution you are using? I'd like to construct a function in the package like `arrayJobID <- getArrayID(type = 'slurm')` to make this extraction a little nicer on the user side.

**Closed by philchalmers** 2024-03-30 13:36 UTC

**Comment by mronkko** [comment] 2024-04-02 06:21
I was not aware that the job configuration is available in environmental variables. This is very useful to know. Thanks. Here is the output of a short test script on my cluster:

```
SLURM_ARRAY_TASK_COUNT  2
SLURM_ARRAY_TASK_ID     1
SLURM_ARRAY_TASK_MAX    2
SLURM_ARRAY_TASK_MIN    1
SLURM_ARRAY_TASK_STEP   1
```

> Do you know what type of array job distribution you are using?

I try to get array jobs to be around 10 000 to 20 000 jobs. Let's assume that I have a simulation with 500 designs and 1000 replications. I would start by splitting each design into 20 replication sets of 50 replications each. So I would run 500*20 = 10 000 jobs consisting of 50 replications each. The array specification for this would be 1-10000. This run produces a majority of what I need, but typically, some of the more challenging designs are not fully complete.

In the second run of the simulation, I increased the replication sets to, e.g., 50 so that each set was just 20 replications. Then I run a script, copied below, that loads all results and checks which replication sets are still missing replications. The jobs corresponding to these replications are then returned. For example, assume that the first design was missing replications 30-50. This means that the following replication set would contain missing replications

Replication sets:
1 (1-20): No missing replications 
2 (21-40): Replications 30-40 are missing
3 (41-60): Replications 41-50 are missing
4 ... 50 : No missing desings 

The array specification would thus be 2-3

So to answer your question, I normally start by running with a job id array consisting of a sequence 1-N. Thereafter, the following runs use array jobs consisting of non-consequtive IDs where the largest ID is typically much larger than in the original run because the replications are split into a larger number of sets.

Here is the script that I use for checking for missing replications and creating an array job specification string.

```
# Aggregates the results as one data file

# Read the simulation designMatrix and the constants (REPLICATIONS and REPLICATION_SETS)  from the parameters file

source("parameters.R")

# Find designs with missing results
  
missingDesigns <- lapply(1:nrow(designMatrix), function(designNumber){
  
  if(! designNumber %in% toCheck)
    return(numeric(0))
    
  allReplications <- 1:REPLICATIONS
  missingReplications <- allReplications
  
  fileName <- paste("Data/Model_Fit_Design_",designNumber,".Rdata",sep="")
  
  if(file.exists(fileName)){
    load(fileName)
    missingReplications <- setdiff(missingReplications,results[,"replication"])
  }
  
  print(paste("Design", designNumber, "has", length(missingReplications),"missing replications."))
  
  missingReplications
  
})


missingBatches <- unlist(lapply(1:nrow(designMatrix), function(designNumber){
  
  allReplications <- 1:REPLICATIONS
  missingReplications <- missingDesigns[[designNumber]]
  
  # Check which batches these belong to
  
  if(REPLICATION_SETS >1)
    replicationsInSets <- split(allReplications, 
                                cut(allReplications, REPLICATION_SETS, 
                                    labels = FALSE))
  else
    replicationsInSets <- list(allReplications)
  
  batchesWithMissing <- which(unlist(lapply(replicationsInSets, function(reps){
    any(reps %in% missingReplications)
  })))
  batchesWithMissing + (designNumber-1)*REPLICATION_SETS
}))


makeDesignString <- function(designsToRun){
  
  # Mark designs that are part of a sequence 
  omit <- designsToRun-1 == c(-1,designsToRun[-length(designsToRun)]) &
    designsToRun+1 == c(designsToRun[-1],-1)
  
  designString <- paste(designsToRun[!omit],
                        ifelse(c(omit[-1],FALSE),"-",",")[!omit],collapse="",sep="")
  designString <- substr(designString,1,nchar(designString)-1)
  designString
}

cat(paste("tail -v -n 2 slurm-",missingBatches,"-*.out",sep="", collapse="\n"))
#cat(paste("rm Model_Fit_Design_",setdiff(1:nrow(designMatrix),missingBatches),
#          ".Rdata",sep="", collapse="\n"), file ="rm.txt")
makeDesignString(missingBatches)
```

**Comment by philchalmers** [comment] 2024-04-02 13:37
Gotcha, thanks. This workflow is something that should be easy to handle with the new `runArraySimulation()` function I've been constructing. I'll make a vignette at some point once I've settled on the complete workflow and helper accoutrements.

**Comment by mronkko** [comment] 2024-04-03 04:46
Thanks. Would you mind posting to this issue once the `runArraySimulation() ` function and the vignette are published so I can test them?

**Comment by philchalmers** [comment] 2024-04-04 18:36
First draft of the vignette added. Install the current dev version and see the attached file for a tutorial (zipped for Github upload).
[Distributing jobs for high-performance computing (HPC) clusters (e.g., via SLURM).zip](https://github.com/philchalmers/SimDesign/files/14875795/Distributing.jobs.for.high-performance.computing.HPC.clusters.e.g.via.SLURM.zip)

**Comment by mronkko** [comment] 2024-04-05 07:42
It looks good.  One useful addition to the vignette would be that the ArrayID is taken from environmental variables.

I also have two comments on the implementation, which I posted as separate issues #36 and #37.
