### ISSUE TITLE
Is it possible to capture all errors when using multiple analysis functions?

### ISSUE THREAD

**Issue by marklhc** [philchalmers/SimDesign#20] opened 2021-10-22 22:11 UTC
Hi Phil, I have another question regarding using multiple analysis functions. In a current project I want to compare the convergence rates of different methods, and since `SimDesign` draws a new sample when one of the analysis functions throws an error. My understanding is that currently `SimDesign` will stop a replication as soon as the first error was found, which means that the convergence rate of each analysis depends on the ordering of the method, as in the following example:

``` r
library(SimDesign)
# SimFunctions(comments=FALSE)

Design <- createDesign(N = c(10, 20, 30))

Generate <- function(condition, fixed_objects = NULL) {
  ret <- with(condition, if (runif(1) > 0.8) rep(NA, N) else rnorm(N))
  ret
}

Analyse.a1 <- function(condition, dat, fixed_objects = NULL) {
  if (any(is.na(dat))) {
    stop("mean did not converge")
  }
  ret <- mean(dat)
  ret
}

Analyse.a2 <- function(condition, dat, fixed_objects = NULL) {
  if (any(is.na(dat))) {
    stop("median did not converge")
  }
  ret <- median(dat)
  ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
  ret <- c(bias = bias(results, 0))
  ret
}

result <- runSimulation(Design,
                        replications = 10, seed = rep(103, 3),
                        generate = Generate, 
                        analyse = list(a1 = Analyse.a1, a2 = Analyse.a2), 
                        summarise = Summarise
)
#> 
#> Design row: 1/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.00s 
#> 
#> Design row: 2/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.01s 
#> 
#> Design row: 3/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.02s
#> 
#> Simulation complete. Total execution time: 0.02s

# Switch the order of a1 and a2
result2 <- runSimulation(Design,
                        replications = 10, seed = rep(103, 3),
                        generate = Generate, 
                        analyse = list(a2 = Analyse.a2, a1 = Analyse.a1), 
                        summarise = Summarise
)
#> 
#> Design row: 1/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.00s 
#> 
#> Design row: 2/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.01s 
#> 
#> Design row: 3/3;   Started: Fri Oct 22 15:04:57 2021;   Total elapsed time: 0.01s
#> 
#> Simulation complete. Total execution time: 0.02s

attr(result, which = "ERROR")
#> # A tibble: 3 × 1
#>   `ERROR: .mean did not converge\n`
#>                               <dbl>
#> 1                                 1
#> 2                                 2
#> 3                                 4
attr(result2, which = "ERROR")
#> # A tibble: 3 × 1
#>   `ERROR: .median did not converge\n`
#>                                 <dbl>
#> 1                                   1
#> 2                                   2
#> 3                                   4
```

<sup>Created on 2021-10-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Would it be possible to add an option so that for a given replication, all functions in the analysis list will run, and then all errors will be recorded? I know I can treat method as another design factor but I want to have the same data sets when comparing the different analysis functions. What I previously have done is to use multiple `tryCatch()` inside the `Analyse()` functions, and threw an error if anyone of the analyses resulted in an error; when multiple functions resulted in errors I just chained the error messages together (and there may be better ways to do it). Curious what you think about that, and whether something like that can be done with multiple analysis functions. 

Thank you very much!

Mark

**Comment by philchalmers** [comment] 2021-11-12 17:09
Hi Mark,

I've been mulling over this issue for a little while now, and decided that the default behaviour when using a list of `analyse` functions should automatically allow the execution of each function regardless of the results from the other independent analysis components. I was initially hesitant to do that as it can potentially add a lot of needless overhead (e.g., comparing an ML estimator versus MCMC; if the former fails then data should be re-drawn immediately until the ML criteria is satisficed, and only then move on to MCMC), but I realize that most of the overhead application is likely special case anyway and should be up to the user to decide the overhead cost. 

Using a modified version of your example above gives the following output:

```r
library(SimDesign)
# SimFunctions(comments=FALSE)

Design <- createDesign(N = c(10, 20, 30))

generate <- function(condition, fixed_objects = NULL) {
    ret <- with(condition, rnorm(N))
    ret
}

Analyse.a1 <- function(condition, dat, fixed_objects = NULL) {
    whc <- sample(c(0, 1, 2, 3), 1, prob = c(.7, .20, .05, .05))
    if (whc == 0) {
        ret <- mean(dat)
    } else if (whc == 1) {
        ret <- t.test() # missing arguments
    } else if (whc == 2) {
        ret <- t.test("invalid") # invalid arguments
    } else if (whc == 3) {
        # throw error manually
        stop("Manual error thrown")
    }
    # manual warnings
    if (sample(c(TRUE, FALSE), 1, prob = c(.1, .9))) {
        warning("This warning happens rarely")
    }
    if (sample(c(TRUE, FALSE), 1, prob = c(.5, .5))) {
        warning("This warning happens much more often")
    }
    ret
}

Analyse.a2 <- function(condition, dat, fixed_objects = NULL) {
    whc <- sample(c(0, 1, 2, 3), 1, prob = c(.7, .20, .05, .05))
    if (whc == 0) {
        ret <- median(dat)
    } else if (whc == 1) {
        ret <- t.test() # missing arguments
    } else if (whc == 2) {
        ret <- t.test("invalid") # invalid arguments
    } else if (whc == 3) {
        # throw error manually
        stop("Manual error thrown")
    }
    ret
}

summarise <- function(condition, results, fixed_objects = NULL) {
    ret <- c(bias = bias(results, 0))
    ret
}

result <- runSimulation(Design,
                        replications = 1000, 
                        generate = generate, 
                        analyse = list(a1 = Analyse.a1, a2 = Analyse.a2), 
                        summarise = summarise)
result

# A tibble: 3 x 9
      N  bias.a1   bias.a2 REPLICATIONS SIM_TIME COMPLETED                      SEED ERRORS WARNINGS
  <dbl>    <dbl>     <dbl>        <int>    <dbl> <chr>                         <int>  <int>    <int>
1    10  0.00184  0.00421          1000     2.73 Fri Nov 12 12:02:43 2021 1842658107   1092      603
2    20 -0.00720 -0.00301          1000     2.80 Fri Nov 12 12:02:46 2021  621640645   1015      618
3    30  0.00649  0.000657         1000     2.89 Fri Nov 12 12:02:48 2021  163788864    997      618

SimExtract(result, 'errors')

   N
1 10
2 20
3 30
  ERROR:  2 INDEPENDENT ERRORS THROWN:   a1.ERROR:   Error in t.test.default("invalid") : not enough 'x' observations\n  a2.ERROR:   Error in t.test.default("invalid") : not enough 'x' observations\n\n
1                                                                                                                                                                                                       4
2                                                                                                                                                                                                       2
3                                                                                                                                                                                                       6

<CLIP...>
```

Much like your previous strategy, the errors are combined into a unified error and counted (where applicable). Makes the errors list a little less readable, but then the problem is more complex so that's the consequence I suppose. Of course, this doesn't quite help your situation 100%, but design-wise I think this behaviour is more appropriate. Let me know what you think before closing this issue off.

**Comment by marklhc** [comment] 2021-11-13 16:37
Hi Phil,

Thank you so much and this is very helpful for my situation. I can do some quick post-processing to compute the error rates with, for instance, "a1.ERROR" and "a2.ERROR" in this example, like below

```
err <- SimExtract(result, 'errors')
# Total errors for each method
cbind(
    err[1],
    a1 = rowSums(err[grep("a1.ERROR", names(err))]),
    a2 = rowSums(err[grep("a2.ERROR", names(err))])
)
#>    N   a1  a2
#> 1 10 1374 303
#> 2 20 1272 270
#> 3 30 1271 289
```

Just to confirm, is the default behaviors now to stop as soon as an error occurs when `Analyse` is one function, but to capture the first errors from all functions when `Analyse` is a list of functions?

Thanks again! The package is great. To your point earlier, I've tried different ways to streamline simulation codes, and this is by far the best I've used.

Mark

**Comment by philchalmers** [comment] 2021-11-13 23:00
> Just to confirm, is the default behaviors now to stop as soon as an error occurs when Analyse is one function, but to capture the first errors from all functions when Analyse is a list of functions?

The new default is that when `Analyse` is a list of functions it will execute and collect all independent error messages from each function execution. Of course, if 1 or more errors are observed than a new dataset will be regenerated until R = `replications` valid datasets are successfully analysed by each function in the `Analyse` list. Does that help?

**Comment by marklhc** [comment] 2021-11-15 21:55
Yes it does. Thank you Phil!

**Closed** 2021-11-15 22:16 UTC
